/* DO NOT EDIT THIS FILE - it is machine generated */
#include <com_umeng_fb_opus_OpusTool.h>
#include <jni.h>
#include <opus.h>
#include "android_log.h"
/*
 * Class:     com_umeng_fb_opus_OpusTool
 * Method:    nativeGetString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_umeng_fb_opus_OpusTool_nativeGetString(
		JNIEnv * env, jobject obj) {
	return (*env)->NewStringUTF(env, "Hello");
}

/*
 * Class:     com_umeng_fb_opus_OpusTool
 * Method:    encode_wav_file
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_umeng_fb_opus_OpusTool_encode_1wav_1file
  (JNIEnv *env, jobject obj, jstring wav_path, jstring opus_path) {
	const char *wav = (*env)->GetStringUTFChars(env, wav_path, 0);
	const char *opus = (*env)->GetStringUTFChars(env, opus_path, 0);

	LOGD("wav_path = %s",wav);
	LOGD("opus_path = %s",opus);
	return encode_wav_file(wav,opus);

}

/*
 * Class:     com_umeng_fb_opus_OpusTool
 * Method:    decode_opus_file
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_umeng_fb_opus_OpusTool_decode_1opus_1file
  (JNIEnv *env, jobject obj, jstring opus_path, jstring wav_path) {
	const char *wav = (*env)->GetStringUTFChars(env, wav_path, 0);
    const char *opus = (*env)->GetStringUTFChars(env, opus_path, 0);

    LOGD("wav_path = %s",wav);
    LOGD("opus_path = %s",opus);
	return decode_opus_file(opus,wav);
}

////Dalvik虚拟机加载C库时，第一件事是调用JNI_OnLoad()函数
//jint JNI_OnLoad(JavaVM* vm, void* reserved) {
//    JNIEnv* env = NULL;//定义JNI Env
//    jint result = JNI_ERR;
//    sVm = vm;
//    /*JavaVM::GetEnv 原型为 jint (*GetEnv)(JavaVM*, void**, jint);
//     * GetEnv()函数返回的  Jni 环境对每个线程来说是不同的，
//     *  由于Dalvik虚拟机通常是Multi-threading的。每一个线程调用JNI_OnLoad()时，
//     *  所用的JNI Env是不同的，因此我们必须在每次进入函数时都要通过vm->GetEnv重新获取
//     *
//     */
//    //得到JNI Env
//    if (vm->GetEnv((void**) &env, JNI_VERSION_1_4) != JNI_OK) {
//    	LOGD("GetEnv failed!");
//        return result;
//    }
//
//    result = JNI_VERSION_1_4;
//
//    return result;
//}
