libOpus_cur_dir = ../libopus
CELT_SOURCES = $(libOpus_cur_dir)/celt/bands.c \
$(libOpus_cur_dir)/celt/celt.c \
$(libOpus_cur_dir)/celt/cwrs.c \
$(libOpus_cur_dir)/celt/entcode.c \
$(libOpus_cur_dir)/celt/entenc.c \
$(libOpus_cur_dir)/celt/kiss_fft.c \
$(libOpus_cur_dir)/celt/laplace.c \
$(libOpus_cur_dir)/celt/mathops.c \
$(libOpus_cur_dir)/celt/mdct.c \
$(libOpus_cur_dir)/celt/modes.c \
$(libOpus_cur_dir)/celt/pitch.c \
$(libOpus_cur_dir)/celt/celt_lpc.c \
$(libOpus_cur_dir)/celt/quant_bands.c \
$(libOpus_cur_dir)/celt/rate.c \
$(libOpus_cur_dir)/celt/vq.c
$(libOpus_cur_dir)/celt/entdec.c \

SILK_SOURCES_FIXED = \
$(libOpus_cur_dir)/silk/fixed/LTP_analysis_filter_FIX.c \
$(libOpus_cur_dir)/silk/fixed/LTP_scale_ctrl_FIX.c \
$(libOpus_cur_dir)/silk/fixed/corrMatrix_FIX.c \
$(libOpus_cur_dir)/silk/fixed/encode_frame_FIX.c \
$(libOpus_cur_dir)/silk/fixed/find_LPC_FIX.c \
$(libOpus_cur_dir)/silk/fixed/find_LTP_FIX.c \
$(libOpus_cur_dir)/silk/fixed/find_pitch_lags_FIX.c \
$(libOpus_cur_dir)/silk/fixed/find_pred_coefs_FIX.c \
$(libOpus_cur_dir)/silk/fixed/noise_shape_analysis_FIX.c \
$(libOpus_cur_dir)/silk/fixed/prefilter_FIX.c \
$(libOpus_cur_dir)/silk/fixed/process_gains_FIX.c \
$(libOpus_cur_dir)/silk/fixed/regularize_correlations_FIX.c \
$(libOpus_cur_dir)/silk/fixed/residual_energy16_FIX.c \
$(libOpus_cur_dir)/silk/fixed/residual_energy_FIX.c \
$(libOpus_cur_dir)/silk/fixed/solve_LS_FIX.c \
$(libOpus_cur_dir)/silk/fixed/warped_autocorrelation_FIX.c \
$(libOpus_cur_dir)/silk/fixed/apply_sine_window_FIX.c \
$(libOpus_cur_dir)/silk/fixed/autocorr_FIX.c \
$(libOpus_cur_dir)/silk/fixed/burg_modified_FIX.c \
$(libOpus_cur_dir)/silk/fixed/k2a_FIX.c \
$(libOpus_cur_dir)/silk/fixed/k2a_Q16_FIX.c \
$(libOpus_cur_dir)/silk/fixed/pitch_analysis_core_FIX.c \
$(libOpus_cur_dir)/silk/fixed/vector_ops_FIX.c \
$(libOpus_cur_dir)/silk/fixed/schur64_FIX.c \
$(libOpus_cur_dir)/silk/fixed/schur_FIX.c

SILK_SOURCES = $(libOpus_cur_dir)/silk/CNG.c \
$(libOpus_cur_dir)/silk/code_signs.c \
$(libOpus_cur_dir)/silk/enc_API.c \
$(libOpus_cur_dir)/silk/encode_indices.c \
$(libOpus_cur_dir)/silk/encode_pulses.c \
$(libOpus_cur_dir)/silk/gain_quant.c \
$(libOpus_cur_dir)/silk/interpolate.c \
$(libOpus_cur_dir)/silk/LP_variable_cutoff.c \
$(libOpus_cur_dir)/silk/NLSF_decode.c \
$(libOpus_cur_dir)/silk/NSQ.c \
$(libOpus_cur_dir)/silk/NSQ_del_dec.c \
$(libOpus_cur_dir)/silk/PLC.c \
$(libOpus_cur_dir)/silk/shell_coder.c \
$(libOpus_cur_dir)/silk/tables_gain.c \
$(libOpus_cur_dir)/silk/tables_LTP.c \
$(libOpus_cur_dir)/silk/tables_NLSF_CB_NB_MB.c \
$(libOpus_cur_dir)/silk/tables_NLSF_CB_WB.c \
$(libOpus_cur_dir)/silk/tables_other.c \
$(libOpus_cur_dir)/silk/tables_pitch_lag.c \
$(libOpus_cur_dir)/silk/tables_pulses_per_block.c \
$(libOpus_cur_dir)/silk/VAD.c \
$(libOpus_cur_dir)/silk/control_audio_bandwidth.c \
$(libOpus_cur_dir)/silk/quant_LTP_gains.c \
$(libOpus_cur_dir)/silk/VQ_WMat_EC.c \
$(libOpus_cur_dir)/silk/HP_variable_cutoff.c \
$(libOpus_cur_dir)/silk/NLSF_encode.c \
$(libOpus_cur_dir)/silk/NLSF_VQ.c \
$(libOpus_cur_dir)/silk/NLSF_unpack.c \
$(libOpus_cur_dir)/silk/NLSF_del_dec_quant.c \
$(libOpus_cur_dir)/silk/process_NLSFs.c \
$(libOpus_cur_dir)/silk/stereo_LR_to_MS.c \
$(libOpus_cur_dir)/silk/stereo_MS_to_LR.c \
$(libOpus_cur_dir)/silk/check_control_input.c \
$(libOpus_cur_dir)/silk/control_SNR.c \
$(libOpus_cur_dir)/silk/init_encoder.c \
$(libOpus_cur_dir)/silk/control_codec.c \
$(libOpus_cur_dir)/silk/A2NLSF.c \
$(libOpus_cur_dir)/silk/ana_filt_bank_1.c \
$(libOpus_cur_dir)/silk/biquad_alt.c \
$(libOpus_cur_dir)/silk/bwexpander_32.c \
$(libOpus_cur_dir)/silk/bwexpander.c \
$(libOpus_cur_dir)/silk/debug.c \
$(libOpus_cur_dir)/silk/decode_pitch.c \
$(libOpus_cur_dir)/silk/inner_prod_aligned.c \
$(libOpus_cur_dir)/silk/lin2log.c \
$(libOpus_cur_dir)/silk/log2lin.c \
$(libOpus_cur_dir)/silk/LPC_analysis_filter.c \
$(libOpus_cur_dir)/silk/LPC_inv_pred_gain.c \
$(libOpus_cur_dir)/silk/table_LSF_cos.c \
$(libOpus_cur_dir)/silk/NLSF2A.c \
$(libOpus_cur_dir)/silk/NLSF_stabilize.c \
$(libOpus_cur_dir)/silk/NLSF_VQ_weights_laroia.c \
$(libOpus_cur_dir)/silk/pitch_est_tables.c \
$(libOpus_cur_dir)/silk/resampler.c \
$(libOpus_cur_dir)/silk/resampler_down2_3.c \
$(libOpus_cur_dir)/silk/resampler_down2.c \
$(libOpus_cur_dir)/silk/resampler_private_AR2.c \
$(libOpus_cur_dir)/silk/resampler_private_down_FIR.c \
$(libOpus_cur_dir)/silk/resampler_private_IIR_FIR.c \
$(libOpus_cur_dir)/silk/resampler_private_up2_HQ.c \
$(libOpus_cur_dir)/silk/resampler_rom.c \
$(libOpus_cur_dir)/silk/sigm_Q15.c \
$(libOpus_cur_dir)/silk/sort.c \
$(libOpus_cur_dir)/silk/sum_sqr_shift.c \
$(libOpus_cur_dir)/silk/stereo_encode_pred.c \
$(libOpus_cur_dir)/silk/stereo_find_predictor.c \
$(libOpus_cur_dir)/silk/stereo_quant_pred.c \
$(SILK_SOURCES_FIXED)
$(libOpus_cur_dir)/silk/code_signs.c \
$(libOpus_cur_dir)/silk/init_decoder.c \
$(libOpus_cur_dir)/silk/decode_core.c \
$(libOpus_cur_dir)/silk/decode_frame.c \
$(libOpus_cur_dir)/silk/decode_parameters.c \
$(libOpus_cur_dir)/silk/decode_indices.c \
$(libOpus_cur_dir)/silk/decode_pulses.c \
$(libOpus_cur_dir)/silk/decoder_set_fs.c \
$(libOpus_cur_dir)/silk/dec_API.c \
$(libOpus_cur_dir)/silk/stereo_decode_pred.c \

OPUS_SOURCES = $(libOpus_cur_dir)/src/opus.c \
$(libOpus_cur_dir)/src/opus_encoder.c \
$(libOpus_cur_dir)/src/opus_multistream.c \
$(libOpus_cur_dir)/src/repacketizer.c
$(libOpus_cur_dir)/src/opus_decoder.c \

libopus_la_SOURCES = $(CELT_SOURCES) $(SILK_SOURCES) $(OPUS_SOURCES)

CFLAGS =-O2 -fvisibility=hidden -W -Wall -Wextra -Wcast-align -externs -Wshadow -Wstrict-prototypes -I$(libOpus_cur_dir)/silk -I$(libOpus_cur_dir)/include -I$(libOpus_cur_dir)/silk/fixed -I$(libOpus_cur_dir)/celt -I$(libOpus_cur_dir)

CXXFLAGS = $(CFLAGS) -DHAVE_CONFIG_H -DUSE_ALLOCA

OBJ_FILES = $(libopus_la_SOURCES:%.c=%.o)

%.o:    %.c
	gcc  $(CXXFLAGS) -o $@ -c $<  

ALL: libopus_dec.a

libopus_dec.a: $(OBJ_FILES)
	ar cr $@ $^
	ranlib $@
	
clean:
	rm -f $(OBJ_FILES) $(libopus_dec.a)
