CELT_SOURCES = celt/bands.c \
celt/celt.c \
celt/cwrs.c \
celt/entcode.c \
celt/entdec.c \
celt/entenc.c \
celt/kiss_fft.c \
celt/laplace.c \
celt/mathops.c \
celt/mdct.c \
celt/modes.c \
celt/pitch.c \
celt/celt_lpc.c \
celt/quant_bands.c \
celt/rate.c \
celt/vq.c

SILK_SOURCES_FIXED = \
silk/fixed/LTP_analysis_filter_FIX.c \
silk/fixed/LTP_scale_ctrl_FIX.c \
silk/fixed/corrMatrix_FIX.c \
silk/fixed/encode_frame_FIX.c \
silk/fixed/find_LPC_FIX.c \
silk/fixed/find_LTP_FIX.c \
silk/fixed/find_pitch_lags_FIX.c \
silk/fixed/find_pred_coefs_FIX.c \
silk/fixed/noise_shape_analysis_FIX.c \
silk/fixed/prefilter_FIX.c \
silk/fixed/process_gains_FIX.c \
silk/fixed/regularize_correlations_FIX.c \
silk/fixed/residual_energy16_FIX.c \
silk/fixed/residual_energy_FIX.c \
silk/fixed/solve_LS_FIX.c \
silk/fixed/warped_autocorrelation_FIX.c \
silk/fixed/apply_sine_window_FIX.c \
silk/fixed/autocorr_FIX.c \
silk/fixed/burg_modified_FIX.c \
silk/fixed/k2a_FIX.c \
silk/fixed/k2a_Q16_FIX.c \
silk/fixed/pitch_analysis_core_FIX.c \
silk/fixed/vector_ops_FIX.c \
silk/fixed/schur64_FIX.c \
silk/fixed/schur_FIX.c

SILK_SOURCES = silk/CNG.c silk/code_signs.c silk/init_decoder.c \
silk/decode_core.c silk/decode_frame.c \
silk/decode_parameters.c silk/decode_indices.c \
silk/decode_pulses.c silk/decoder_set_fs.c silk/dec_API.c \
silk/enc_API.c silk/encode_indices.c silk/encode_pulses.c \
silk/gain_quant.c silk/interpolate.c silk/LP_variable_cutoff.c \
silk/NLSF_decode.c silk/NSQ.c silk/NSQ_del_dec.c silk/PLC.c \
silk/shell_coder.c silk/tables_gain.c silk/tables_LTP.c \
silk/tables_NLSF_CB_NB_MB.c silk/tables_NLSF_CB_WB.c \
silk/tables_other.c silk/tables_pitch_lag.c \
silk/tables_pulses_per_block.c silk/VAD.c \
silk/control_audio_bandwidth.c silk/quant_LTP_gains.c \
silk/VQ_WMat_EC.c silk/HP_variable_cutoff.c silk/NLSF_encode.c \
silk/NLSF_VQ.c silk/NLSF_unpack.c silk/NLSF_del_dec_quant.c \
silk/process_NLSFs.c silk/stereo_LR_to_MS.c \
silk/stereo_MS_to_LR.c silk/check_control_input.c \
silk/control_SNR.c silk/init_encoder.c silk/control_codec.c \
silk/A2NLSF.c silk/ana_filt_bank_1.c silk/biquad_alt.c \
silk/bwexpander_32.c silk/bwexpander.c silk/debug.c \
silk/decode_pitch.c silk/inner_prod_aligned.c silk/lin2log.c \
silk/log2lin.c silk/LPC_analysis_filter.c \
silk/LPC_inv_pred_gain.c silk/table_LSF_cos.c silk/NLSF2A.c \
silk/NLSF_stabilize.c silk/NLSF_VQ_weights_laroia.c \
silk/pitch_est_tables.c silk/resampler.c \
silk/resampler_down2_3.c silk/resampler_down2.c \
silk/resampler_private_AR2.c silk/resampler_private_down_FIR.c \
silk/resampler_private_IIR_FIR.c \
silk/resampler_private_up2_HQ.c silk/resampler_rom.c \
silk/sigm_Q15.c silk/sort.c silk/sum_sqr_shift.c \
silk/stereo_decode_pred.c silk/stereo_encode_pred.c \
silk/stereo_find_predictor.c silk/stereo_quant_pred.c \
$(SILK_SOURCES_FIXED)

OPUS_SOURCES = src/opus.c \
src/opus_decoder.c \
src/opus_encoder.c \
src/opus_multistream.c \
src/repacketizer.c

CELT_HEAD = \
celt/arch.h \
celt/bands.h \
celt/celt.h \
include/opus_types.h \
include/opus_defines.h \
include/opus_custom.h \
celt/cwrs.h \
celt/ecintrin.h \
celt/entcode.h \
celt/entdec.h \
celt/entenc.h \
celt/fixed_debug.h \
celt/fixed_generic.h \
celt/float_cast.h \
celt/_kiss_fft_guts.h \
celt/kiss_fft.h \
celt/laplace.h \
celt/mathops.h \
celt/mdct.h \
celt/mfrngcod.h \
celt/modes.h \
celt/os_support.h \
celt/pitch.h \
celt/celt_lpc.h \
celt/quant_bands.h \
celt/rate.h \
celt/stack_alloc.h \
celt/vq.h \
celt/static_modes_float.h \
celt/static_modes_fixed.h

SILK_HEAD = \
silk/debug.h \
silk/control.h \
silk/errors.h \
silk/API.h \
silk/typedef.h \
silk/define.h \
silk/main.h \
silk/PLC.h \
silk/structs.h \
silk/tables.h \
silk/tuning_parameters.h \
silk/Inlines.h \
silk/MacroCount.h \
silk/MacroDebug.h \
silk/macros.h \
silk/pitch_est_defines.h \
silk/resampler_private.h \
silk/resampler_rom.h \
silk/resampler_structs.h \
silk/SigProc_FIX.h \
silk/fixed/main_FIX.h \
silk/fixed/structs_FIX.h \
silk/float/main_FLP.h \
silk/float/structs_FLP.h \
silk/float/SigProc_FLP.h

OPUS_HEAD = \
include/opus.h \
include/opus_multistream.h \
src/opus_private.h

libopus_la_SOURCES = $(CELT_SOURCES) $(SILK_SOURCES) $(OPUS_SOURCES)
#libopus_la_LDFLAGS = -no-undefined -version-info 2:0:2
noinst_HEADERS = $(OPUS_HEAD) $(SILK_HEAD) $(CELT_HEAD)

CFLAGS = -g -O2 -fvisibility=hidden -W -Wall -Wextra -Wcast-align -externs -Wshadow -Wstrict-prototypes -I./silk -I./include -I./silk/fixed -I./celt -I.

CXXFLAGS = $(CFLAGS) -DHAVE_CONFIG_H -DUSE_ALLOCA

OBJ_FILES = $(libopus_la_SOURCES:%.c=%.o)

%.o:    %.c
	gcc  $(CXXFLAGS) -o $@ -c $<  

ALL: libopus.a

libopus.a: $(OBJ_FILES)
	ar cr $@ $^
	ranlib $@
	
clean:
	rm -f $(OBJ_FILES) $(libopus.a)
